travis:
  secure:
    BINSTAR_TOKEN: ZkFNi5peIKjNm4lPcbZ0ZnP+jOKHdesROqOh4Y02k13mu83l9HKTNCocCfdy7rH+OtJGubxxfJW3xEt8aU8ExDTTPGsRrWlu6S7rb9URtMLFs5YeB4dyMsL7fCqrDitG+tZuzVlAiAXmFLd3IksAhfgJ4wBXEPMhuj7ftrmlpGiSy8sTioMfSuv7dbewwUpYHz9XiZeob8Cql9j4SHRZkzoK6xeLumE1BmdUublZJrMAGfXLdyPrgFj31C0L/G1b5CWcw32bJNH0ulTdK5KDqhMCz1crTurPlZQSXcSHZCgqa5crGhVI1hBT4FvV0JLiNNPNpCEprrvW30y3iza7sqIPeXy6yc6SXbtxQ7xFojc5GmRNILEkDEyrcMF2/xinJZ3enneH0AJd4Zm42nQSTM/1ZCWLukZXIz0x0suW1s3Xl350E0gCC/ZKM/vH/PQldazvcDbjDOVSiOlnFTal4OSkAhxjvjGIlD0TGFKH1YnNco5L86UUNLK6XPUWkwkmw1xIS0F56XA7h4BKoysY3mWGZmHfVzUll9hLgm2ibdAvDf0pS4buk2UP7lRBfr3641cT6kqprD73ynmTT/r6pfAUo3GX8wi3b2nYNmPmmW4/994++KwMJGdwG9R2WMm79xjNs0mOPLlMrp8nBQdpirMdPx5YjHcbYylWgCuawj0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
